scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    max_x: 2.0
    max_y: 0.5
    max_z: 0.3
    min_x: 0.5
    min_y: -0.5
    min_z: -0.28
    invert: true